Day52/app/posts/__init__.py
from flask import Blueprint
post_blueprint = Blueprint('posts', __name__, url_prefix='')
from app.posts import views

Day52/app/posts/views.py
from datetime import datetime
from flask import current_app, request, render_template, redirect, send_from_directory, url_for, flash
from app.models import Post, Category,  db
from app.posts import post_blueprint
from werkzeug.utils import secure_filename
import os

# ALLOWED_EXTENSIONS = set(['png', 'jpg', 'jpeg', 'gif'])

# def allowed_file(filename):
# 	return '.' in filename and filename.rsplit('.', 1)[1].lower() in ALLOWED_EXTENSIONS


@post_blueprint.route('/', endpoint='posts_list')
def posts_list():
    posts = Post.get_all_posts()
    return render_template('posts/index.html', posts=posts)


@post_blueprint.route('/contact')
def contact_us():
    return render_template('contacts/contact_us.html')


@post_blueprint.route('/about')
def about_us():
    return render_template('contacts/about_us.html')


@post_blueprint.route('/details/<int:id>', endpoint='post_details')
def post_details(id):
    post = Post.query.get_or_404(id)
    return render_template('posts/post_details.html', post=post)


@post_blueprint.route('/create', endpoint='post_create', methods=['GET', 'POST'])
def create_post():
    categories = Category.get_all_categories()

    if 'title' in request.form and 'body' in request.form and 'image' in request.files and 'category' in request.form:
        title = request.form['title']
        body = request.form['body']
        image = request.files['image']
        category_id = request.form['category']

        if not title or not body or not category_id:
            return render_template('posts/create_post.html', error='Title, category and body are required fields')

        if image.filename == '':
            return render_template('posts/create_post.html', error='No selected image')

        if image:
            filename = secure_filename(image.filename)
            filename = f"{datetime.now().strftime('%Y%m%d%H%M%S')}.{filename}"
            image_path = os.path.join(
                current_app.config["UPLOADED_PHOTOS_DEST"], filename)
            image.save(image_path)

            # filename = secure_filename(image.filename)
            # image_path = os.path.join(current_app.config['UPLOAD_FOLDER'], filename)
            # image.save(image_path)

            new_post = Post(title=title, body=body,
                            image=filename, category_id=category_id, created_at=datetime.utcnow())
            db.session.add(new_post)
            db.session.commit()

            return redirect(url_for('posts.posts_list'))
        else:
            return render_template('posts/create_post.html', categories=categories, error='Image file type not allowed')

    return render_template('posts/create_post.html', categories=categories, error='Title, body, category and image are required fields')


@post_blueprint.route('/uploads/<filename>')
def send_uploaded_file(filename):
    return send_from_directory(current_app.config["UPLOADED_PHOTOS_DEST"], filename)

# @post_blueprint.route('/display/<filename>')
# def display_image(filename):
# 	return redirect(url_for('static', filename='uploads/' + filename), code=301)


@post_blueprint.route('/edit/<int:id>', endpoint='post_edit', methods=['GET', 'POST'])
def edit_post(id):
    post = Post.query.get_or_404(id)
    categories = Category.get_all_categories()

    if request.method == 'POST':
        title = request.form['title']
        body = request.form['body']
        image = request.files['image']
        category_id = request.form['category']

        if not title or not body:
            flash('Title and body are required fields', 'error')
        else:
            post.title = title
            post.body = body
            post.category_id = category_id
            if image:
                os.remove(
                    current_app.config["UPLOADED_PHOTOS_DEST"]+'/'+post.image)
                filename = secure_filename(image.filename)
                image.save(os.path.join(
                    current_app.config["UPLOADED_PHOTOS_DEST"], filename))
                post.image = filename

            db.session.commit()
            flash('Post updated successfully', 'success')
            return redirect(url_for('posts.post_details', id=post.id))

    return render_template('posts/edit_post.html', categories=categories, post=post)


@post_blueprint.route('/delete/<int:id>', endpoint='post_delete', methods=['GET', 'POST'])
def delete_post(id):
    post = Post.query.get_or_404(id)
    if request.method == 'POST':
        if post.image:
            os.remove(
                current_app.config["UPLOADED_PHOTOS_DEST"]+'/'+post.image)

        db.session.delete(post)
        db.session.commit()
        return redirect(url_for('posts.posts_list'))
    return render_template('posts/delete_post.html', post=post)

Day52/app/templates/posts/create_post.html
{% extends "layouts/base.html" %}{% block title %} Create Post {% endblock %} {% block body %}

<h1 class="text-center">Create a New Post</h1>
<form method="POST" class="container" action="{{ url_for('posts.post_create') }}" enctype="multipart/form-data">
  <label for="title" class="form-label">Title:</label>
  <input type="text" name="title" class="form-control" required />

  <label for="body" class="form-label">Body:</label>
  <textarea name="body" class="form-control" required></textarea>

  <label for="image" class="form-label">Image:</label>
  <input type="file" name="image" accept=".jpg, .jpeg, .png, .gif" class="form-control" required />

  <label for="category" class="form-label">Category:</label>
  <select name="category" class="form-select" required>
    <option value="" disabled selected>Select a category</option>
    {% for category in categories %}
    <option value="{{ category.id }}">{{ category.name }}</option>
    {% endfor %}
  </select>

  <input type="submit" value="Create Post" class="form-control btn btn-outline-info mt-2" />
</form>
{% endblock %}

Day52/app/templates/posts/delete_post.html
{% extends "layouts/base.html" %} {% block title %}Delete Post{% endblock %} {% block body %}

<h1 class="text-center">Delete Post: {{post.title}}</h1>
<h3 class="text-center">Are you sure you want to delete this post?</h3>
<form method="POST" class="container justify-content-center d-flex flex-column" enctype="multipart/form-data">
  <button type="submit" class="btn btn-outline-danger my-2">Delete</button>
  <a href="{{ url_for('posts.post_details', id=post.id) }}" class="btn btn-outline-dark">Cancel</a>
</form>

{% endblock %}

Day52/app/templates/posts/edit_post.html
{% extends "layouts/base.html" %} {% block title %}Edit Post{% endblock %} {% block body %}

<h1 class="text-center">Edit Post: {{ post.title }}</h1>
<form method="POST" class="container" enctype="multipart/form-data">
  <label for="title" class="form-label">Title:</label>
  <input type="text" name="title" class="form-control" value="{{ post.title }}" required />

  <label for="body" class="form-label">Body:</label>
  <textarea name="body" class="form-control" required>{{ post.body }}</textarea>

  <label for="image" class="form-label">Image:</label>
  <input type="file" name="image" accept=".jpg, .jpeg, .png, .gif" class="form-control" />

  <label for="category" class="form-label">Category:</label>
  <select name="category" class="form-select" required>
    <option value="" disabled selected>Select a category</option>
    {% for category in categories %}
    <option value="{{ category.id }}" {% if post.category_id == category.id %} selected {% endif %} />{{ category.name }}</option>
    {% endfor %}
  </select>

  <input type="submit" value="Update Post" class="form-control btn btn-outline-info mt-2" />
</form>
{% endblock %}

Day52/app/templates/posts/index.html
{% extends "layouts/base.html" %}{% block title %} Posts {% endblock %} {% block body %}
<a class="btn btn-outline-dark form-control my-3 w-50 justify-content-center d-flex m-auto" href="{{url_for('posts.post_create')}}">Create New Post</a>
<div class="container d-flex gap-2">
  {% for post in posts %}
  <div class="card" style="width: 18rem">
    <img src="{{ url_for('posts.send_uploaded_file', filename=post.image) }}" class="card-img-top h-75 w-100" alt="..." />
    <div class="card-body">
      <h5 class="card-title">{{post.title}}</h5>
      <p class="card-text">{{post.body}}</p>
      <a href="{{ url_for('posts.post_details', id=post.id) }}" class="btn btn-outline-primary">Details</a>
      <a href="{{ url_for('posts.post_delete', id=post.id) }}" class="btn btn-outline-danger">Delete</a>
      <a href="{{ url_for('posts.post_edit', id=post.id) }}" class="btn btn-outline-warning">Edit</a>
    </div>
  </div>
  {% endfor %}
</div>
{% endblock %}

Day52/app/templates/posts/post_details.html
{% extends "layouts/base.html" %}{% block title %} Post Details {% endblock %} {% block body %}
<div class="container d-grid my-4">
  <div class="row">
    <div class="col-6">
      <img src="{{ url_for('posts.send_uploaded_file', filename=post.image) }}" class="w-100" alt="..." />
    </div>
    <div class="list-group col-6">
      <h4 class="list-group-item">Title: {{post.title}}</h4>
      <a class="list-group-item">Body: {{post.body}}</a>
      <div class="list-group-item">
        Category:
        <a class="list-group-item btn btn-outline-warning" href="{{ url_for('category.category_details', id=post.category_id) }}">{{post.category}}</a>
      </div>
      <a href="{{ url_for('posts.post_delete', id=post.id) }}" class="btn btn-outline-danger list-group-item">Delete</a>
      <a href="{{ url_for('posts.post_edit', id=post.id) }}" class="btn btn-outline-warning list-group-item">Edit</a>
      <a href="{{ url_for('posts.posts_list') }}" class="btn btn-outline-primary list-group-item">Go Back</a>
    </div>
  </div>
</div>
{% endblock %}